# Generated by Django 2.2.3 on 2019-07-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travllo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
